name: specwrk-single-node

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  specwrk-single-node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      ## SPECWRK STEP ##
      - name: Restore specwrk
        uses: actions/cache@v4
        with:
          path: |
            .specwrk/report.json
          key: specwrk-${{ hashFiles('spec/**/*_spec.rb') }}
          restore-keys: |
            specwrk-${{ hashFiles('spec/**/*_spec.rb') }}
            specwrk-
      ## /SPECWRK STEP ##

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.4
          bundler-cache: true

      ## SPECWRK STEP ##
      - name: Run tests via specwrk start
        run: bundle exec specwrk start --count 2 spec/
      ## /SPECWRK STEP ##
